### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by BurnhamR** [Minecraft-Modded-War/LootableBodies#1]
Fixes:
- [ ] - Fix bodies despawning randomly
- [ ] - Fix bodies teleporting around
- [ ] - Fix bodies not spawning
- [ ] - Fix bodies spawning in ground

Remove:
- [ ] - Remove all corpse damage configs and just make bodies pretty much invincible(allow /kill, void fall, and stuff)
- [ ] - Remove bodies "Health" 
- [ ] - Remove EnderIO integration
- [ ] - Remove bones and flesh config and spawning.

Add:

- [ ] - Config Despawn time to bodies with loot
- [ ] - Config Despawn time to bodies without loot
